#
# pass for whitelisted (public) routes
# block for blacklisted routes
#
rules:
  pass:
    - api/v2/barong/identity
    - api/v2/peatio/public
    - api/v2/ranger/public
    - api/v2/applogic/public
    - api/v2/arke/public
    - api/v2/barong/management
    - api/v2/peatio/management
  #block:
  #  - api/v2/barong/management
  #  - api/v2/peatio/management
 
  # When blocked, it shows like this:
  #  Response body --
  #   {"errors":["authz.permission_denied"]}
